@Poc.TaskHub.Api_HostAddress = http://localhost:5022

### Retrieve all tasks
GET {{Poc.TaskHub.Api_HostAddress}}/api/tasks
Accept: application/json

### Retrieve task by ID
GET {{Poc.TaskHub.Api_HostAddress}}/api/tasks/{id}
Accept: application/json

### Create a new task
POST {{Poc.TaskHub.Api_HostAddress}}/api/tasks
Content-Type: application/json
Accept: application/json

{
  "description": "New task description",
  "content": "New task content",
  "isCompleted": false
}