namespace Poc.TaskHub.Eai.Infrstructure.Abstractions
{
    /// <summary>
    /// Defines an interface for adapters responsible for executing queries and returning responses.
    /// This abstraction allows for flexible integration with various data sources or external systems.
    /// </summary>
    /// <typeparam name="TQuery">The type of the query to be executed.</typeparam>
    /// <typeparam name="TResponse">The type of the response returned by the adapter.</typeparam>
    public interface IAdapter<TQuery, TResponse>
    {
        /// <summary>
        /// Executes the specified query and returns the corresponding response.
        /// </summary>
        /// <param name="query">The query to be executed.</param>
        /// <returns>The response generated by executing the query.</returns>
        TResponse Execute(TQuery query);
    }
}